# Versioned Properties

# Fabric Properties, check https://fabricmc.net/develop/
build.yarn=1.20.1+build.10
build.fabric_api=0.92.3+1.20.1

# Additional Dependencies Properties
# cit-resewn, check https://modrinth.com/mod/cit-resewn/versions?g=1.20.1
dep.cit-resewn=1.2.2+1.20.1
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.20.1
dep.modmenu=7.2.2
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.20.1
dep.yacl=3.6.6+1.20.1-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.20.1
dep.sodium=mc1.20.1-0.5.13-fabric
# ears, check https://modrinth.com/mod/ears/versions?g=1.20.1
dep.ears=1.4.7+fabric-1.20