plugins {
	id "net.lopymine.mossy-plugin-core" version "$mossy_plugin_version"
}

mossyDependencies {
	minecraft = stonecutter.current.version.toString()
	mappings = prop("build.yarn")
	lombok = prop("base.lombok_version")
	fabricApi = prop("build.fabric_api")
	fabricLoader = prop("build.fabric_loader")

	additional {
		// - By default, every additional project dependency ("dep.modId" from gradle.properties) will use
		// - Modrinth Maven and "modImplementation" configuration name
		// - If you want to override mod configuration name, you can do this:

		//override("modCompileOnly", "just_mod_id")

		// - It will do this:
		// - modImplementation("maven.modrinth:modId:version") -> modCompileOnly("maven.modrinth:modId:version")

		// - Or if you want to disable it and handle by yourself, just disable it auto handling:

		//disable("just_mod_id")

		disable("cit-resewn")
	}
}

mossyResources {
	//expandFiles = ["custom", "file", "patterns", "here"]
}

repositories {
	// Mixin^2
	maven {
		name = "Mixin Squared"
		url = "https://maven.bawnorton.com/releases"
	}
}

dependencies {
	// Mixin^2
	include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${prop("build.mixin_squared")}")))

	// CIT Resewn
	def cit = prop("dep.cit-resewn")
	if (cit != "unknown") {
		modImplementation "maven.modrinth:cit-resewn:${cit}"
		modImplementation "maven.modrinth:cit-resewn-defaults:${cit}"
	}
}

String prop(String key) {
	return findProperty(key).toString()
}