plugins {
	id "net.lopymine.mossy-plugin-core" version "$mossy_plugin_version"
}

mossyDependencies {
	minecraft = stonecutter.current.project.substring(stonecutter.current.project.indexOf("-") + 1)
	lombok = prop("base.lombok_version")

	fabricApi = prop("build.fabric_api")
	fabricLoader = prop("build.fabric_loader")

	forge = prop("build.forge")
	parchment = prop("build.parchment")

	additional {
		//override("modCompileOnly", "yacl")
		override("mossyCompileOnly", "iris")
		override("mossyCompileOnly", "sodium")
	}
}

repositories {
	// Mixin^2
	maven {
		name = "Mixin Squared"
		url = "https://maven.bawnorton.com/releases"
	}
}

dependencies {
	// Mixin^2
	if (sc.current.project.contains("fabric")) {
		include(implementation(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-fabric:${prop("build.mixin_squared")}")))
	} else {
		compileOnly(annotationProcessor("com.github.bawnorton.mixinsquared:mixinsquared-common:${prop("build.mixin_squared")}"))
		implementation(jarJar("com.github.bawnorton.mixinsquared:mixinsquared-neoforge:${prop("build.mixin_squared")}"))
	}
}

String prop(String key) {
	return findProperty(key).toString()
}