# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=26.3.0.8-beta

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.3&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.3&l=neoforge
dep.yacl=3.9.7+26.3-neoforge
# sodium, check https://modrinth.com/mod/sodium/versions?g=26.3&l=neoforge
dep.sodium=mc26.3-0.9.3-alpha.1-neoforge
