# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=21.1.234
build.parchment=2024.11.17

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.1&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.1&l=neoforge
dep.yacl=3.8.2+1.21.1-neoforge
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.1&l=neoforge
dep.sodium=mc1.21.1-0.6.13-neoforge

# iris, check https://modrinth.com/mod/iris/versions?g=1.21.1&l=neoforge
dep.iris=1.8.14-beta.1+1.21.1-neoforge
