# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.116.13+1.21.1

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.1&l=fabric
dep.modmenu=11.0.4
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.1&l=fabric
dep.yacl=3.8.2+1.21.1-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.1&l=fabric
dep.sodium=mc1.21.1-0.8.12-beta.2-fabric
# iris, check https://modrinth.com/mod/iris/versions?g=1.21.1&l=fabric
dep.iris=1.8.14-beta.1+1.21.1-fabric
