# Versioned Properties

# Fabric Properties, check https://fabricmc.net/develop/
build.yarn=1.21.3+build.2
build.fabric_api=0.114.0+1.21.3

# Additional Dependencies Properties
# cit-resewn, check https://modrinth.com/mod/cit-resewn/versions?g=1.21.3
dep.cit-resewn=unknown
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.3
dep.modmenu=12.0.0
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.3
dep.yacl=3.8.0+1.21.3-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.3
dep.sodium=mc1.21.3-0.6.8-fabric
# ears, check https://modrinth.com/mod/ears/versions?g=1.21.3
dep.ears=unknown