# Versioned Properties

# Fabric Properties, check https://fabricmc.net/develop/
build.yarn=1.21.4+build.8
build.fabric_api=0.116.1+1.21.4

# Additional Dependencies Properties
# cit-resewn, check https://modrinth.com/mod/cit-resewn/versions?g=1.21.4
dep.cit-resewn=unknown
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.4
dep.modmenu=13.0.2
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.4
dep.yacl=3.8.0+1.21.4-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.4
dep.sodium=mc1.21.4-0.6.7-fabric
# ears, check https://modrinth.com/mod/ears/versions?g=1.21.4
dep.ears=1.4.7+fabric-1.21.4