# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.yarn=1.21.8+build.1
build.fabric_api=0.130.0+1.21.8

# Additional Dependencies Properties
# cit-resewn, check https://modrinth.com/mod/cit-resewn/versions?g=1.21.8&l=fabric
dep.cit-resewn=unknown
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.8&l=fabric
dep.modmenu=15.0.0-beta.3
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.8&l=fabric
dep.yacl=3.8.0+1.21.6-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.8&l=fabric
dep.sodium=mc1.21.6-0.6.13-fabric
# ears, check https://modrinth.com/mod/ears/versions?g=1.21.8&l=fabric
dep.ears=unknown