# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.fabric_api=0.152.2+26.2

# Additional Dependencies Properties
# cit-resewn, check https://modrinth.com/mod/cit-resewn/versions?g=26.2&l=fabric
dep.cit-resewn=unknown
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.2&l=fabric
dep.modmenu=20.0.0-beta.3
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.2&l=fabric
dep.yacl=3.9.4+26.2-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=26.2&l=fabric
dep.sodium=mc26.2-0.9.0-fabric
# ears, check https://modrinth.com/mod/ears/versions?g=26.2&l=fabric
dep.ears=unknown
