# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Fabric Properties, check https://fabricmc.net/develop/
build.yarn=1.21.9+build.1
build.fabric_api=0.134.0+1.21.9

# Additional Dependencies Properties
# cit-resewn, check https://modrinth.com/mod/cit-resewn/versions?g=1.21.9&l=fabric
dep.cit-resewn=unknown
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.21.9&l=fabric
dep.modmenu=16.0.0-rc.1
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.21.9&l=fabric
dep.yacl=3.8.0+1.21.9-fabric
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.21.9&l=fabric
dep.sodium=mc1.21.9-0.7.0-fabric
# ears, check https://modrinth.com/mod/ears/versions?g=1.21.9&l=fabric
dep.ears=unknown