# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# Forge Properties, check https://files.minecraftforge.net/net/minecraftforge/forge/index_1.20.1.html
build.forge=1.20.1-47.4.20
build.parchment=2023.09.03

# Additional Dependencies Properties
# iris, check https://modrinth.com/mod/iris/versions?g=1.20.1&l=forge
dep.iris=unknown
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=1.20.1&l=forge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=1.20.1&l=forge
dep.yacl=3.6.6+1.20.1-forge
# sodium, check https://modrinth.com/mod/sodium/versions?g=1.20.1&l=forge
dep.sodium=unknown
# embeddium, check https://modrinth.com/mod/embeddium/versions?g=1.20.1&l=forge
dep.embeddium=0.3.31+mc1.20.1
# oculus, check https://modrinth.com/mod/oculus/versions?g=1.20.1&l=forge
dep.oculus=1.20.1-1.8.0
