# Versioned Properties
# Tip: You can set any dependency value to "[UPDATE]"
# and reload Gradle to update only it's value.

# NeoForge Properties, check https://neoforged.net/
build.neoforge=26.2.0.7-beta

# Additional Dependencies Properties
# modmenu, check https://modrinth.com/mod/modmenu/versions?g=26.2&l=neoforge
dep.modmenu=unknown
# yacl, check https://modrinth.com/mod/yacl/versions?g=26.2&l=neoforge
dep.yacl=3.9.4+26.2-neoforge
# sodium, check https://modrinth.com/mod/sodium/versions?g=26.2&l=neoforge
dep.sodium=mc26.2-0.9.1-beta.2-neoforge
